# Generated by Django 4.0.6 on 2022-07-14 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SigOther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('met', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('break_up', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Meetings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('rating', models.IntegerField(verbose_name='Rating out of 10')),
                ('details', models.TextField(max_length=250)),
                ('sig_other', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.sigother')),
            ],
        ),
    ]
