# Generated by Django 4.0.6 on 2022-07-14 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_trait_alter_meetings_options_sigother_traits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trait',
            old_name='designation',
            new_name='desig',
        ),
    ]
