# Generated by Django 4.0.6 on 2022-07-14 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_designation_trait_desig'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trait',
            old_name='desig',
            new_name='designation',
        ),
    ]
