# Generated by Django 4.0.6 on 2022-07-14 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_desig_trait_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='trait',
            name='name',
            field=models.CharField(default='trait', max_length=50),
            preserve_default=False,
        ),
    ]
