# Generated by Django 4.0.6 on 2022-07-18 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_trait_designation_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='sigOther',
            new_name='relationship',
        ),
    ]
