# Generated by Django 4.0.6 on 2022-07-18 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_trait_designation_alter_trait_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trait',
            name='designation',
            field=models.CharField(choices=[('P', 'Positive'), ('B', 'Negative'), ('N', 'Neutral')], default='P', max_length=1, verbose_name='Is this trait:'),
        ),
        migrations.AlterField(
            model_name='trait',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
